Table
lobovskiy/react-json-tree pull request #1
Opened 2022-02-24 14:39 UTC by lobovskiy

2022-02-25 10:09 UTC, Ann040294 requested changes

2022-02-25 10:09 UTC, Ann040294 commented on src/components/app/app.js
> +        <button className="ru" onClick={ () => handleChangeLanguage('ru') }></button>
Хм

2022-02-25 10:09 UTC, Ann040294 commented on src/components/app/app.scss
> +  button {
Хм

2022-02-25 10:09 UTC, Ann040294 commented on src/components/app/app.scss
> +    &.ru {
Хм-хм-хм

2022-02-25 10:09 UTC, Ann040294 commented on src/components/app/app.scss
> +.App {
хм

2022-02-25 10:09 UTC, Ann040294 commented on src/components/app/app.js
> +        <button className="ru" onClick={ () => handleChangeLanguage('ru') }></button>
а если муууультиязный будет

2022-02-25 10:09 UTC, Ann040294 commented on src/components/app/app.scss
> +.app-spinner {
не тут или не так

2022-02-25 10:09 UTC, Ann040294 commented on src/components/app/app.scss
> +.app-menu {
тут ли?

2022-02-25 10:09 UTC, Ann040294 commented on src/components/app/app.scss
> +.change-language {
и придерживайся одного стиля
то откуда взято - не имеет значения, сейчас это в твоем приложении

2022-02-25 10:09 UTC, Ann040294 commented on src/components/pages/family-table-page/family-table-page.js
> +import { useTranslation } from 'react-i18next';
предложение: внешние группировать

2022-02-25 10:09 UTC, Ann040294 commented on src/components/pages/family-table-page/family-table-page.scss
> +// .table {
если не ошибаюсь форматер уже работает
и это уже не нужно ..

2022-02-25 10:09 UTC, Ann040294 commented on src/components/pages/index.js
> +import FamilyTablePage from './family-table-page';
pick: у тебя все предложение заточено под Family может и нет смысла добавлять это слово в название?

2022-02-25 10:09 UTC, Ann040294 commented on src/components/pages/main-page/main-page.js
> +    <div>Hi!</div>
давай хоть красивый хай сделаем 😁

2022-02-25 10:09 UTC, Ann040294 commented on src/components/table/table-columns.js
> +function TableColumns({ row, configColumns }) {
давайка добавим проптайпс
не против formatter
но вроде как это сущ-е, но выполняет действие
тип бы подсказал что ожидает

2022-02-25 10:09 UTC, Ann040294 commented on src/components/table/table.js
> +
давай рассмотрим опциональный кейс если ничего нет то все же покажем что здесь что то может быть 
настройка будет общая - на таблицу и строки

2022-02-25 10:09 UTC, Ann040294 commented on src/components/table/table.scss
> +
ойёй

2022-02-25 10:09 UTC, Ann040294 commented on src/dto/table-dto.js
> +const tableDTO = data => ({
все же это функция

2022-02-25 10:09 UTC, Ann040294 commented on src/helpers/formatters/gender-formatter.js
> +function genderFormatter(cell, key) {
пересмотреть
что совпадает ?

2022-02-25 10:09 UTC, Ann040294 commented on src/helpers/formatters/gender-formatter.js
> +function genderFormatter(cell, key) {
и это ф-я

2022-02-25 10:09 UTC, Ann040294 commented on src/locales/en/translation.json
> +  "Table header": "Family members",
ключикикики

2022-02-25 10:09 UTC, Ann040294 commented on src/locales/en/translation.json
> +  "Table header": "Family members",
причем оооочень понятный ключик

2022-02-25 10:09 UTC, Ann040294 commented on src/locales/en/translation.json
> +  "Table header": "Family members",
если не будет перевода вдруг покажется какой то не описательный ключик

2022-02-25 10:09 UTC, Ann040294 commented on src/store/reducer.js
> +  loading: false
подумать

2022-02-25 10:09 UTC, Ann040294 commented on src/store/reducer.js
> +      return { ...state, loading: true }
куда то поехали

2022-03-01 14:29 UTC, lobovskiy commented on src/locales/en/translation.json
> +  "Table header": "Family members",
решено в ветке tree

2022-03-21 10:57 UTC, lobovskiy commented on src/store/reducer.js
> +      return { ...state, loading: true }
приехали назад

2022-03-22 06:08 UTC, lobovskiy commented on src/components/app/app.js
> +        <button className="ru" onClick={ () => handleChangeLanguage('ru') }></button>
вынес в компонент

2022-03-22 06:08 UTC, lobovskiy commented on src/components/app/app.scss
> +  button {
уехало в компонент

2022-03-22 06:08 UTC, lobovskiy commented on src/components/app/app.scss
> +    &.ru {
и не вернулось

2022-03-22 06:15 UTC, lobovskiy commented on src/components/app/app.scss
> +.App {
что-то отрефакторил

2022-03-22 06:15 UTC, lobovskiy commented on src/components/app/app.scss
> +.app-spinner {
а здесь не помню что не так (

2022-03-22 06:21 UTC, lobovskiy commented on src/store/reducer.js
> +      return { ...state, loading: true }
в diffs уехало, в режиме просмотра все ок, в редакторе тож. не знаю че с ним

2022-03-22 06:24 UTC, lobovskiy commented on src/components/app/app.scss
> +.app-menu {
что-то тож отрефакторил

2022-03-22 06:24 UTC, lobovskiy commented on src/components/app/app.scss
> +.change-language {
ок. уехало в отдельный компонент

2022-03-22 06:37 UTC, lobovskiy commented on src/components/pages/family-table-page/family-table-page.scss
> +// .table {
да, удалил

2022-03-22 06:51 UTC, lobovskiy commented on src/components/pages/index.js
> +import FamilyTablePage from './family-table-page';
уговорила

2022-03-22 06:52 UTC, lobovskiy commented on src/components/pages/family-table-page/family-table-page.js
> +import { useTranslation } from 'react-i18next';
эт как?

2022-03-22 12:10 UTC, lobovskiy commented on src/components/pages/main-page/main-page.js
> +    <div>Hi!</div>
сделал покрасивей.
словарь с переводом в последних ветках уже поприличнее.

2022-03-22 12:13 UTC, lobovskiy commented on src/dto/table-dto.js
> +const tableDTO = data => ({
да, уже понял))

2022-03-22 13:04 UTC, lobovskiy commented on src/components/table/table.scss
> +
+

2022-03-22 13:13 UTC, lobovskiy commented on src/store/reducer.js
> +  loading: false
разделил состояния в следующих ветках

2022-03-22 14:23 UTC, lobovskiy commented on src/components/app/app.scss
> +.App {
все разделил и властвую

2022-03-22 14:24 UTC, lobovskiy commented on src/components/app/app.scss
> +.app-spinner {
тоже отделил все

2022-03-22 14:24 UTC, lobovskiy commented on src/components/table/table-columns.js
> +function TableColumns({ row, configColumns }) {
проптайпсов напилю в ветке с редакс тулкитом

2022-03-22 14:25 UTC, lobovskiy commented on src/components/table/table.js
> +
ну и тут собсно тоже в последних ветках приколочу проптайпсы

2022-03-23 10:35 UTC, merged