Family app with sync tree page
lobovskiy/react-json-tree pull request #2
Opened 2022-03-24 13:01 UTC by lobovskiy

Add sync tree page with fetching data from local JSON file

2022-03-24 13:25 UTC, Ann040294 requested changes

2022-03-24 13:25 UTC, Ann040294 commented on src/components/tree/tree.js
> +        target.parentNode.classList.toggle('tree__node_expanded');
а тут ?

2022-03-24 13:25 UTC, Ann040294 commented on src/dto/tree-dto.js
> +export default getTreeItem;
файл на каждую такую функцию? [ 🦒 '' ]

2022-03-24 13:25 UTC, Ann040294 commented on src/helpers/create-tree.js
> +    if (!indexedItems.includes(arr[i]?.id)) {
может упаковать?

2022-03-24 13:25 UTC, Ann040294 commented on src/saga/familySaga.js
> +  yield call(() => new Promise(res => setTimeout(res, 1000)));
а тут?

2022-03-24 13:25 UTC, Ann040294 commented on src/store/reducer.js
>        return { ...state, loading: true }
??

2022-03-24 13:25 UTC, Ann040294 commented on src/components/tree/tree.js
> +          if (child.classList.contains('hidden')) {
может другой вариант?

2022-03-24 14:17 UTC, lobovskiy commented on src/components/tree/tree.js
> +        target.parentNode.classList.toggle('tree__node_expanded');
поправил

2022-03-24 14:17 UTC, lobovskiy commented on src/dto/tree-dto.js
> +export default getTreeItem;
объединил

2022-03-24 14:19 UTC, lobovskiy commented on src/saga/familySaga.js
> +  yield call(() => new Promise(res => setTimeout(res, 1000)));
задилеил

2022-03-24 14:28 UTC, lobovskiy commented on src/store/reducer.js
>        return { ...state, loading: true }
state в последних ветках разделен, сейчас каждой странице свой loading сделал

2022-03-24 14:29 UTC, lobovskiy commented on src/components/tree/tree.js
> +          if (child.classList.contains('hidden')) {
здесь не понял

2022-03-24 14:29 UTC, lobovskiy commented on src/helpers/create-tree.js
> +    if (!indexedItems.includes(arr[i]?.id)) {
здесь не оч понял

2022-03-25 09:09 UTC, Ann040294 commented on src/saga/familySaga.js
> +  yield call(() => new Promise(res => setTimeout(res, 1000)));
окей
я еще про утилиту вспомнила но она у тебя позже подучается

2022-03-25 09:13 UTC, Ann040294 approved these changes

2022-03-25 09:13 UTC, merged