App with tree async page
lobovskiy/react-json-tree pull request #3
Opened 2022-03-25 14:19 UTC by lobovskiy

2022-03-28 08:35 UTC, Ann040294 requested changes

2022-03-28 08:35 UTC, Ann040294 commented on src/api/get-children.js
> +export default getChildren;
default ?

2022-03-28 08:35 UTC, Ann040294 commented on src/components/tree/tree-node.js
> +                { tree__node_expanded: node.isExpanded }
придерживайся стилистики

2022-03-28 08:35 UTC, Ann040294 commented on src/pages/tree-async-page/tree-async-page.js
> +  const tree = isLoading
может все же пересмотреть этот подход ?

2022-03-28 08:35 UTC, Ann040294 commented on src/server/handlers/create-tree.js
> +      if (branch[i]?.children?.length) {
а раньше не упадет тогда?)

2022-03-28 08:35 UTC, Ann040294 commented on src/server/handlers/create-tree.js
> +          delete child.children;
точно подходит?

2022-03-28 08:35 UTC, Ann040294 commented on src/server/index.js
> +export default serverRequest;
тут ок

2022-03-28 08:35 UTC, Ann040294 commented on src/server/table.js
> +}
тут можно просто map(getTableItem) 😁 _pic_

2022-03-28 08:35 UTC, Ann040294 commented on src/store/reducer.js
> +            if (branch[i].id === id) {
точно нужны ли оба?

2022-03-28 08:35 UTC, Ann040294 commented on src/store/reducer.js
> +      let newTree = async
а можно только условие на значение

2022-03-28 08:35 UTC, Ann040294 commented on src/store/reducer.js
> +              branch[i].isExpanded = !branch[i].isExpanded; // isExpanded изначально undefined, надо подумать
что надумал?

2022-03-28 08:56 UTC, lobovskiy commented on src/server/table.js
> +}
век живи - век учись

2022-03-28 13:41 UTC, lobovskiy commented on src/api/get-children.js
> +export default getChildren;
поправил

2022-03-28 13:50 UTC, lobovskiy commented on src/store/reducer.js
> +            if (branch[i].id === id) {
вот и поговорили

2022-03-28 14:07 UTC, lobovskiy commented on src/components/tree/tree-node.js
> +                { tree__node_expanded: node.isExpanded }
ок

2022-03-28 14:52 UTC, lobovskiy commented on src/pages/tree-async-page/tree-async-page.js
> +  const tree = isLoading
пересмотрел, но можно потом еще подумать...

2022-03-28 14:53 UTC, lobovskiy commented on src/pages/tree-async-page/tree-async-page.js
> +  const tree = isLoading
пока что реакт перестравивает всю структуру данных, можно подумать, как не загружать уже загруженное...

2022-03-28 14:55 UTC, Ann040294 commented on src/pages/tree-async-page/tree-async-page.js
> +  const tree = isLoading
зависит от частоты обновления данных

2022-03-28 14:55 UTC, lobovskiy commented on src/server/handlers/create-tree.js
> +          delete child.children;
да)

2022-03-28 14:56 UTC, lobovskiy commented on src/server/index.js
> +export default serverRequest;
ок

2022-03-28 14:58 UTC, Ann040294 commented on src/api/get-children.js
> +export default getChildren;
а где?

2022-03-28 14:59 UTC, Ann040294 commented on src/pages/tree-async-page/tree-async-page.js
> +  const tree = isLoading
+у тебя же уже есть для этого инфа... ну если не хочется повторно запрашивать

2022-03-28 15:06 UTC, lobovskiy commented on src/server/handlers/create-tree.js
> +      if (branch[i]?.children?.length) {
подправил

2022-03-29 08:29 UTC, lobovskiy commented on src/store/reducer.js
> +              branch[i].isExpanded = !branch[i].isExpanded; // isExpanded изначально undefined, надо подумать
пока так оставлю

2022-03-29 08:41 UTC, Ann040294 approved these changes

2022-03-29 08:41 UTC, merged